import praw
import pandas as pd

# --- 1) Reddit API Credentials ---
reddit = praw.Reddit(
    client_id='',
    client_secret='',
    user_agent=''
)

urls = [
    "https://www.reddit.com/gallery/1jqwbas",
    "https://www.reddit.com/r/OpenAI/comments/1jqaszf/anyone_else_getting_stuck_on_creating_image_on_a/",
    "https://www.reddit.com/r/OpenAI/comments/1jqtfym/besides_studio_ghibli_lets_see_your_images_in/",
    "https://www.reddit.com/gallery/1jr348c",
    "https://www.reddit.com/gallery/1jrs2u9",
    "https://www.reddit.com/r/OpenAI/comments/1jpid1h/question_for_researchers_using_ai/",
    "https://www.reddit.com/gallery/1jpby8b",
    "https://www.reddit.com/r/OpenAI/comments/1jqitfb/give_a_pin_feature_where_users_can_pin_their/",
    "https://www.reddit.com/r/OpenAI/comments/1jp1zsi/infographics_with_the_4o_image_generator/",
    "https://www.reddit.com/r/OpenAI/comments/1jq17qx/image_gen_v2_out/",
    "https://www.reddit.com/r/OpenAI/comments/1jpw7ft/how_do_i_turn_off_improved_memory/",
    "https://www.reddit.com/gallery/1jqpdpe",
    "https://www.reddit.com/r/OpenAI/comments/1jp4axw/why_are_my_sora_images_low_resolution/",
    "https://www.reddit.com/gallery/1jppfpv",
    "https://www.reddit.com/r/OpenAI/comments/1jqdazu/mckinsey_company_the_state_of_ai_2025/",
    "https://www.reddit.com/r/OpenAI/comments/1jsfa20/because_a_picture_is_worth_a_thousand_words/",
    "https://www.reddit.com/r/OpenAI/comments/1jpeszp/systematically_prompting_ais_to_become_more/",
    "https://www.reddit.com/r/OpenAI/comments/1jqeghp/anyone_else_not_able_to_generate_younger_family/",
    "https://www.reddit.com/r/OpenAI/comments/1jqnxgy/new_jobs_created_by_ai_that_arent_prompt/",
    "https://www.reddit.com/r/OpenAI/comments/1jpa3nc/ai_will_make_privacy_the_new_luxury_item/",
    "https://www.reddit.com/gallery/1jrdkc4",
    "https://www.reddit.com/r/OpenAI/comments/1jrt9l5/how_do_gemini_gems_compare_against_custom_gpts/",
    "https://www.reddit.com/gallery/1jr98yp",
    "https://www.reddit.com/gallery/1jscwas",
    "https://www.reddit.com/r/OpenAI/comments/1jqf9i4/til_openai_prepaid_credits_expires/",
    "https://www.reddit.com/r/OpenAI/comments/1jptapu/paid_customer_prompts_should_have_priority_over/",
    "https://www.reddit.com/r/OpenAI/comments/1jrxgiw/plus_users_are_still_stuck_with_32k_context/",
    "https://www.reddit.com/r/OpenAI/comments/1jpc2l2/is_ai_having_any_real_negative_impact_on_anyones/",
    "https://www.reddit.com/r/OpenAI/comments/1jqresi/what_happened_to_my_canvas_files/",
    "https://www.reddit.com/r/OpenAI/comments/1jrsez7/is_this_a_plausible_solution_to_the_context/",
    "https://www.reddit.com/r/OpenAI/comments/1jp5vsp/interesting_fact_picture_generation_isnt/",
    "https://www.reddit.com/r/OpenAI/comments/1jrj41u/virtual_scroll_for_browser_version/",
    "https://www.reddit.com/r/OpenAI/comments/1jr92go/fresh_account_couldnt_make_api_calls_wont_give_a/",
    "https://www.reddit.com/r/OpenAI/comments/1jqdn2b/content_policy_roulette/",
    "https://www.reddit.com/r/OpenAI/comments/1jse2qr/new_image_generator_not_available_in_the_mac/",
    "https://www.reddit.com/r/OpenAI/comments/1jpznkx/testing_manus_on_automating_systematic_challenge/",
    "https://www.reddit.com/r/OpenAI/comments/1jsc3rt/we_can_make_ghibli_style_but_what_about_jojo/",
    "https://www.reddit.com/r/OpenAI/comments/1jsb1jf/new_llama_model/",
    "https://www.reddit.com/r/OpenAI/comments/1js49gj/reduced_gpt_45_orion_rate_limits/",
    "https://www.reddit.com/gallery/1jp9spg",
    "https://www.reddit.com/r/OpenAI/comments/1jp45z7/do_pro_users_face_cooldowns_too/",
    "https://www.reddit.com/r/OpenAI/comments/1jr751j/azure_openai_embeddings_endpoint_gives_error/",
    "https://www.reddit.com/r/OpenAI/comments/1jqrdhe/gpt_plus_user/",
    "https://www.reddit.com/r/OpenAI/comments/1jsdfgh/any_library_to_pass_tools_automatically_to_gpts/",
    "https://www.reddit.com/r/OpenAI/comments/1jpiqfm/how_can_i_use_gpt_in_my_work/",
    "https://www.reddit.com/r/OpenAI/comments/1jry707/has_anyone_been_asked_do_you_like_this_models/",
    "https://www.reddit.com/r/OpenAI/comments/1jpnkbf/openai_plans_to_release_openweight_language_model/",
    "https://www.reddit.com/r/OpenAI/comments/1jqrh55/all_professionals_might_soon_be_parttime_junior/",
    "https://www.reddit.com/r/OpenAI/comments/1jp7eeo/deep_research_bugged_when_writing_sources/",
    "https://www.reddit.com/gallery/1jpxp6l",
    "https://www.reddit.com/r/OpenAI/comments/1js723m/how_to_write_like_human/",
    "https://www.reddit.com/r/OpenAI/comments/1jqfdnw/imagine_gaming_for_years_only_to_realize_every/",
    "https://www.reddit.com/r/OpenAI/comments/1jowgfw/did_someone_unplug_the_100b_data_center/",
    "https://www.reddit.com/r/OpenAI/comments/1jr8bkr/i_would_prefer_a_literesearch_product_from_openai/",
    "https://www.reddit.com/r/OpenAI/comments/1jptnmo/monday_gpt_randomly_appeared/",
    "https://www.reddit.com/r/OpenAI/comments/1jr1xai/anthropic_research_paper_reasoning_models_dont/",
    "https://www.reddit.com/r/OpenAI/comments/1jpj6wv/the_new_image_tool_has_gotten_a_massive_nerf_it/",
    "https://www.reddit.com/gallery/1joyw3l",
    "https://www.reddit.com/gallery/1jqflus",
    "https://www.reddit.com/r/OpenAI/comments/1jqu1ta/why_i_love_ai_as_a_poor_gig_economy_artist_who_is/",
    "https://www.reddit.com/r/OpenAI/comments/1jqcopo/anyone_using_the_tts_api_keep_getting_quota_error/",
    "https://www.reddit.com/r/OpenAI/comments/1jp2hnq/how_do_you_take_these_ghibli_or_star_wars/",
    "https://www.reddit.com/r/OpenAI/comments/1jptv5c/petition_to_nerf_the_image_generation_content/",
    "https://www.reddit.com/r/OpenAI/comments/1jpqssy/its_down_yes/",
    "https://www.reddit.com/gallery/1jq6ge1",
    "https://www.reddit.com/gallery/1jqc2so",
    "https://www.reddit.com/r/OpenAI/comments/1jr7bm8/webinar_today_an_ai_agent_that_joins_across/",
    "https://www.reddit.com/r/OpenAI/comments/1jqowv8/i_built_an_opensource_operator_that_can_use/",
    "https://www.reddit.com/r/OpenAI/comments/1jrungc/the_peak_of_content_filters_with_their_new_image/",
    "https://www.reddit.com/r/OpenAI/comments/1jqnd0x/ai_all_in_one/",
    "https://www.reddit.com/r/OpenAI/comments/1jrsq1o/theres_strong_likelihood_that_the_quasar_alpha/",
    "https://www.reddit.com/r/OpenAI/comments/1jqr16w/what_is_the_daily_limit_for_image_generation_for/",
    "https://www.reddit.com/r/OpenAI/comments/1jpwspl/what_other_styles_have_yall_gotten_to_work_dragon/",
    "https://www.reddit.com/r/OpenAI/comments/1jsaduf/the_essential_role_of_logic_agents_in_enhancing/",
    "https://www.reddit.com/r/OpenAI/comments/1js9ftc/ai_is_automating_our_jobs_but_values_need_to/",
    "https://www.reddit.com/r/OpenAI/comments/1js7dax/suggestion_desktop_app_for_linux/",
    "https://www.reddit.com/r/OpenAI/comments/1js2pug/extract_handwriting_from_pdfs/",
    "https://www.reddit.com/r/OpenAI/comments/1jqplbe/how_much_of_the_internet_is_indexed_by_openai_in/",
    "https://www.reddit.com/r/OpenAI/comments/1jrjwai/just_here_to_say_ive_been_having_fun_interacting/",
    "https://www.reddit.com/r/OpenAI/comments/1jqnyxt/not_sure_if_using_ai_for_fusion_360_design_is_a/",
    "https://www.reddit.com/r/OpenAI/comments/1jrjcff/is_the_new_image_generator_available_as_an_api_yet/",        
    "https://www.reddit.com/r/OpenAI/comments/1jrfgyn/o3_pro_coming_soon/",
    "https://www.reddit.com/r/OpenAI/comments/1jpqeqy/4o_is_getting_a_lot_better/",
    "https://www.reddit.com/r/OpenAI/comments/1jse7wf/why_responses_api_use_more_tokens/",
    "https://www.reddit.com/r/OpenAI/comments/1jrxtrc/issues_with_just_one_generation_at_a_time/",
    "https://www.reddit.com/r/OpenAI/comments/1jp3neh/two_questions_about_sora/",
    "https://www.reddit.com/r/QNX/comments/1its8lk/wfi_behaves_like_nop_on_qnx_80/",
    "https://www.reddit.com/r/QNX/comments/1h36kqq/build_and_installrun_example_of_simple_program_on/",
    "https://www.reddit.com/r/QNX/comments/15ls2m8/a_wish_open_source_qnx/",
    "https://www.reddit.com/r/QNX/comments/68rv4e/i_want_to_use_qnx_for_my_project_noncommercial/",
    "https://www.reddit.com/r/LangChain/comments/1j64ll7/openai_api_fully_used/",
    "https://www.reddit.com/r/QNX/comments/1j7uwe5/check_if_ethernet_cable_connected/",
    "https://www.reddit.com/r/QNX/comments/1j354mc/some_basic_qnx8_coding_tutorials/",
    "https://www.reddit.com/r/ycombinator/comments/1isqtyf/got_an_enterprise_pilot_but_they_want_nda_how/",        
    "https://www.reddit.com/r/react/comments/17zrvl1/dalle_3_is_not_supported_by_openai_playground/",
    "https://www.reddit.com/r/commandline/comments/1bnsxj6/sengpt_chatgpt_in_your_terminal_no_openai_api_key/",    
    "https://www.reddit.com/r/QNX/comments/f2rlpw/qnx_project_in_visual_studio_code/",
    "https://www.reddit.com/r/QNX/comments/1i6xzkr/spi_driver_spibcm2711_doesnt_seem_to_load_in/",
    "https://www.reddit.com/r/ChatGPT/comments/18jdfex/openai_prompt_engineering_guide/",
    "https://www.reddit.com/r/QNX/comments/8vn6jf/does_anyone_have_a_3rd_party_repository_for_621/",
    "https://www.reddit.com/r/QNX/comments/1h9virg/experience_running_qnx_in_vm/",
    "https://www.reddit.com/r/QNX/comments/1i1wjxq/nano/",
    "https://www.reddit.com/r/LocalLLaMA/comments/1jf9ozd/aichat_generate_a_conversation_between_two_llms/",       
    "https://www.reddit.com/r/ChatGPT/comments/1b1di6u/help_me_create_an_assistat_insturctions_for/",
    "https://www.reddit.com/r/QNX/comments/1j20qb/help_can_anyone_suggest_a_pcie_card_that_works/",
    "https://www.reddit.com/r/ChatGPT/comments/13jkxs6/key_takeways_from_openai_ceos_3hour_senate/",
    "https://www.reddit.com/r/servicenow/comments/1gyz7w3/building_a_servicenowopenai_integration_my/",
    "https://www.reddit.com/r/ChatGPTPro/comments/1cuarai/gpt4o_missing_in_azure_openai_playground/",
    "https://www.reddit.com/r/ChatGPTPro/comments/10zi8cb/chatgpt_plus_vs_openai_playground_both_in_paid/",        
    "https://www.reddit.com/r/QNX/comments/1hl3t31/where_can_i_download_qnx_momentics_and_the/",
    "https://www.reddit.com/r/QNX/comments/i3ux78/interfacing_into_my_cars_qnx_powered_toyota/",
    "https://www.reddit.com/r/QNX/comments/1c807rp/need_help_with_sshd_and_security_policies/",
    "https://www.reddit.com/r/QNX/comments/1jpr9if/qnx_raspberry_pi_4_wifi_hotspot_anyone_has_the/",
    "https://www.reddit.com/r/aipromptprogramming/comments/1jm5mrf/openai_api_image_generation/",
    "https://www.reddit.com/r/OpenWebUI/comments/1ix0p2a/full_integration_proxy_server_for_converting/",
    "https://www.reddit.com/gallery/1ichm8v",
    "https://www.reddit.com/r/QNX/comments/mldx6f/for_the_ones_that_are_just_becoming_familiar_with/",
    "https://www.reddit.com/r/QNX/comments/1j2kjbz/rpi4qnx8_how_to_set_keyboard_layout/",
    "https://www.reddit.com/gallery/1jkhpm3",
    "https://www.reddit.com/r/Nuxt/comments/1jfwunr/nuxt_3_cloudflare_pages_whatwgurl_error_blocking/",
    "https://www.reddit.com/r/QNX/comments/1jbygz8/death_pulse_not_loadable_to_raspbery_pi_target/",
    "https://www.reddit.com/r/GPT/comments/15daonf/openai_playground_skins/",
    "https://www.reddit.com/r/QNX/comments/1h4jzf3/consistent_quick_start_rpi4_ip_address/",
    "https://www.reddit.com/r/QNX/comments/ijdyty/emulate_qnx_425/",
    "https://www.reddit.com/r/homeassistant/comments/1jq7o3p/psa_turn_on_enable_web_search_in_your_openai/",       
    "https://www.reddit.com/r/ChatGPT/comments/1ibj4io/unpopular_opinion_deepseek_has_rateffed_openais/",
    "https://www.reddit.com/r/QNX/comments/1hxuldb/this_qnx_channel_seems_pretty_quiet/",
    "https://www.reddit.com/r/redditenfrancais/comments/181fbmz/openai_il_ny_a_pas_de_mode_sombre_actuellement/",  
    "https://www.reddit.com/r/Paperlessngx/comments/1hrd18d/paperlessai_an_automated_document_analyzer_for/",      
    "https://www.reddit.com/r/PowerApps/comments/1feonjv/it_is_insanely_easy_to_use_the_openai_api_in/",
    "https://www.reddit.com/r/QNX/comments/mtz9he/how_to_get_ntoaarch64gdb_binary_file/",
    "https://www.reddit.com/r/LocalLLaMA/comments/1cr5ic7/access_to_gpt4o_via_openai_playground/",
    "https://www.reddit.com/r/QNX/comments/1izg9yp/i_booted_qnx8_on_my_raspberry_pi_4_now_what/",
    "https://www.reddit.com/r/QNX/comments/1j4wiwb/arm64qnx_mprotect_give_permission_denied/",
    "https://www.reddit.com/r/QNX/comments/1hd7icf/bsp_for_raspberry_pi_4/",
    "https://www.reddit.com/r/QNX/comments/1jchsxr/gpio_output_raspberry_pi/",
    "https://www.reddit.com/r/ChatGPT/comments/10zi9kw/chatgpt_vs_openai_playground_paid_versions/",
    "https://www.reddit.com/r/AICatalyst/comments/1idhmrj/deepseeks_200_iq_move_openai_sdk_hack/",
    "https://www.reddit.com/r/ChatGPT/comments/1ayvvlt/stunspots_guide_to_the_openai_playground/",
    "https://www.reddit.com/r/ChatGPT/comments/1240mak/openai_playground_system_vs_user_input_areas/",
    "https://www.reddit.com/r/QNX/comments/714b96/how_to_change_the_video_mode_from_the_cli/",
    "https://www.reddit.com/r/QNX/comments/1h4l09k/overlaying_root_paths_in_qnx/",
    "https://www.reddit.com/r/QNX/comments/1fi08bb/qnx6_networking/",
    "https://www.reddit.com/r/QNX/comments/yvi01y/for_those_fascinated_by_the_qnx_demodisk_of_the/",
    "https://www.reddit.com/r/QNX/comments/11xen2/14mb_disk/",
    "https://www.reddit.com/r/ChatGPT/comments/1cr4hfd/openai_unveils_gpt4o_free_ai_for_everyone/",
    "https://www.reddit.com/r/LLMDevs/comments/1iju7o3/how_to_improve_openai_api_response_time/",
    "https://www.reddit.com/r/ChatGPTPro/comments/1daagd4/getting_openai_playground_to_behave_consistently/",      
    "https://www.reddit.com/gallery/17bzq9t",
    "https://www.reddit.com/r/QNX/comments/2ww3t8/qnxgdb_questions/",
    "https://www.reddit.com/r/QNX/comments/1ag8fzb/looking_for_assistance_debugging_potential/",
    "https://www.reddit.com/r/QNX/comments/15llr58/qnx_to_revilatize_old_pcs/",
    "https://www.reddit.com/r/QNX/comments/c8097a/compiling_integrating_samba_for_cifs_3x_in_qnx/",
    "https://www.reddit.com/r/n8n/comments/1i4mpqb/openai_api_limit/",
    "https://www.reddit.com/r/csMajors/comments/1h8jdwf/we_landed_openai_boys_and_girls/",
    "https://www.reddit.com/r/QNX/comments/snpdcr/student_who_wants_to_learn_qnx/",
    "https://www.reddit.com/r/QNX/comments/11u60dr/qnx_demodisk_utilities/",
    "https://www.reddit.com/r/ChatGPT/comments/1j3o8tv/psa_you_dont_need_pro_to_access_gpt45_anyone_can/",
    "https://www.reddit.com/r/Python/comments/1ix4m99/opensource_reverse_proxy_to_remove_sensitive_data/",
    "https://www.reddit.com/r/OutOfTheLoop/comments/1i8dpk1/what_is_up_with_so_many_big_tech_ceos_suddenly/",      
    "https://www.reddit.com/r/selfhosted/comments/1i6ggyh/got_deepseek_r1_running_locally_full_setup_guide/",      
    "https://www.reddit.com/r/QNX/comments/7qnnd9/how_to_install_7x/",
    "https://www.reddit.com/r/ClaudeAI/comments/1gvikyn/magicapi_aigateway_now_supports_anthropic_use_it/",        
    "https://www.reddit.com/r/ChatGPT/comments/14agito/meta_will_make_their_next_llm_free_for_commercial/",        
    "https://www.reddit.com/r/QNX/comments/1jqji9c/required_safety_certifications_for_autonomous/",
    "https://www.reddit.com/r/Python/comments/17g9utj/squeezing_water_from_stone_managing_openai_rate/",
    "https://www.reddit.com/r/ChatGPT/comments/1fxbj60/i_do_not_trust_openai/",
    "https://www.reddit.com/r/ChatGPTJailbreak/comments/1i864ew/breaking_news_china_releases_an_open_source/",     
    "https://www.reddit.com/r/QNX/comments/d3sv4r/does_momentics_7_support_powerpc_processors/",
    "https://www.reddit.com/r/QNX/comments/36gqip/how_to_get_memory_information_out_of_qnx/",
    "https://www.reddit.com/r/ClaudeAI/comments/1j2aitd/claude_rate_limits_often_but_openai_rate_limits/",
    "https://www.reddit.com/r/ChatGPTCoding/comments/1ig83w5/openai_pricing_and_usage_for_appbot_creation/",       
    "https://www.reddit.com/r/LocalLLaMA/comments/1jfmbg8/orpheustts_openai_api_edition/",
    "https://www.reddit.com/r/Affine/comments/1hlnu28/selfhost_openai_api_key/",
    "https://www.reddit.com/r/ArtificialInteligence/comments/1i8mp8p/deepseek_overtakes_openai/",
    "https://www.reddit.com/r/QNX/comments/1glfgqz/unable_to_create_context_error_when_i_execute_a/",
    "https://www.reddit.com/r/QNX/comments/1ikf49i/interruptattachevent_behavior/",
    "https://www.reddit.com/r/LocalLLaMA/comments/1gxwhqz/introducing_ogem_your_universal_ai_model_gateway/",      
    "https://www.reddit.com/r/QNX/comments/1i5t86f/qnx_screen_issue/",
    "https://www.reddit.com/r/ChatGPT/comments/1383obf/openai_lost_540m_in_2022_will_need_100b_more_to/",
    "https://www.reddit.com/r/JEENEETards/comments/1iq4h8p/guys_i_wanna_make_a_therapy_ai_with_openai/",
    "https://www.reddit.com/r/PromptEngineering/comments/13a98li/promptsandboxio_openai_playground_on_steroids/",  
    "https://www.reddit.com/r/ChatGPT/comments/1ggixzy/ama_with_openais_sam_altman_kevin_weil_srinivas/",
    "https://www.reddit.com/r/QNX/comments/1emibnt/is_web_browser_development_only_available_in_sdp/",
    "https://www.reddit.com/r/OpenAIDev/comments/18m3k9v/openai_playground_the_assistant_keeps_sending_me/",       
    "https://www.reddit.com/r/QNX/comments/7ucsdp/qnx_425g_r05_how_to_make_a_program_pdm_autostart/",
    "https://www.reddit.com/r/ChatGPT/comments/180g1z2/breaking_the_chaos_at_openai_is_out_of_control/",
    "https://www.reddit.com/r/QNX/comments/1iiyng9/qnx_and_java/",
    "https://www.reddit.com/r/OpenWebUI/comments/1jfmskw/orpheustts_openai_api_edition_plus_a_special/",
    "https://www.reddit.com/r/MachineLearning/comments/13qhyek/d_diff_between_openai_official_chatgpt_and_azure/", 
    "https://www.reddit.com/r/OpenAIDev/comments/1j9jo25/openai_api_so_incredibly_slow/",
    "https://www.reddit.com/r/remNote/comments/1g7lz7x/openai_api_key/",
    "https://www.reddit.com/r/LangChain/comments/17npapw/made_a_library_for_managing_openai_rate_limits/",
    "https://www.reddit.com/r/ChatGPT_Pioneers/comments/15cqtdo/dive_into_ai_with_openai_playground_courses/",     
    "https://www.reddit.com/r/QNX/comments/1h32a2q/a_couple_of_handy_resources/",
    "https://www.reddit.com/r/QNX/comments/1gl76uy/qnx_everywhere_the_latest_qnx_is_free_now/",
    "https://www.reddit.com/r/QNX/comments/1ibjhdf/couple_of_letters_doesnt_work_on_a_keyboard/",
    "https://www.reddit.com/r/aws/comments/1gviijg/use_aws_bedrock_with_openai_sdk_with_no_code/",
    "https://www.reddit.com/r/QNX/comments/2x8x2x/student_intern_working_for_company_using_qnx_and/",
    "https://www.reddit.com/r/stocks/comments/1imh8zt/elon_muskled_group_makes_974_billion_bid_for/",
    "https://www.reddit.com/r/QNX/comments/1ikh3ju/pcie_and_usb_ddk/",
    "https://www.reddit.com/r/ChatGPT/comments/181nqnx/so_it_turns_out_the_openai_drama_really_was_about/",        
    "https://www.reddit.com/r/privacy/comments/1dga57h/elon_musk_threatens_to_ban_iphones_over_openai/",
    "https://www.reddit.com/r/QNX/comments/1ilhr6u/spi_not_found/",
    "https://www.reddit.com/r/QNX/comments/10gto4f/will_qnx_receive_any_new_versions/",
    "https://www.reddit.com/r/QNX/comments/1j416hj/i_have_a_burning_question/",
    "https://www.reddit.com/r/ChatGPT/comments/192pwr1/just_paid_50_for_credits_for_openai_playground/",
    "https://www.reddit.com/r/chrome_extensions/comments/1hwc43m/i_just_built_this_friendlyai_extension_need_your/",
    "https://www.reddit.com/r/QNX/comments/1ieps24/learning_resources/",
    "https://www.reddit.com/r/copilotstudio/comments/1d7vyrv/azure_openai_playground_copilot_studio/",
    "https://www.reddit.com/r/ArtificialInteligence/comments/1dtxnrw/openai_playground_chat_vs_assistants_inconsistent/",
    "https://www.reddit.com/r/ChatGPT/comments/15cj3do/advantages_of_openai_playground/",
    "https://www.reddit.com/r/readwise/comments/1hidv13/automating_highlight_tagging_with_openai_api_key/",        
    "https://www.reddit.com/r/technepal/comments/1gqb6zq/openai_api_key_free/",
    "https://www.reddit.com/r/QNX/comments/1j0abea/anyone_using_vs_code_for_visual_debugging_python/",
    "https://www.reddit.com/r/ChatGPT/comments/1bpsf4m/gpt4_openai_playground_vs_claude_opus/",
    "https://www.reddit.com/r/ChatGPT/comments/13tlszv/linking_an_external_document_to_chatgpt_or_openai/",        
    "https://www.reddit.com/r/QNX/comments/1g540pj/qnx_8_raspberry_pi/",
    "https://www.reddit.com/gallery/11n88xd",
    "https://www.reddit.com/r/AutoGenAI/comments/1jluiuh/free_openai_api_alternatives/",
    "https://www.reddit.com/r/ArtificialInteligence/comments/13bi5vg/breakdown_of_openai_api_usage/",
    "https://www.reddit.com/r/QNX/comments/106gwqo/request_for_qnx_wallpaper_thanks/",
    "https://www.reddit.com/r/singularity/comments/1h8d3gj/openai_staff_member_claims_that_they_have/",
    "https://www.reddit.com/r/ChatGPT/comments/1itu8gl/looking_for_an_alternative_to_openai_api_for_a/",
    "https://www.reddit.com/r/replit/comments/1j58kp6/replit_is_using_someone_elses_openai_api_keys_in/",
    "https://www.reddit.com/r/QNX/comments/1h332lc/ds3231_rtcc_module_for_the_raspberry_pi4/",
    "https://www.reddit.com/r/QNX/comments/12166my/enable_cache_mechanism/",
    "https://www.reddit.com/r/OpenAIDev/comments/13gab10/introducing_aifunction_a_nodejs_utility_to/",
    "https://www.reddit.com/r/QNX/comments/1exsuh2/using_qnx_as_file_server/",
    "https://www.reddit.com/r/QNX/comments/1e71fnq/qnx_momentics_ide_wont_connect_to_qemu_virtual/",
    "https://www.reddit.com/r/QNX/comments/p7agtu/qnx_424_hwinfo/",
    "https://www.reddit.com/r/QNX/comments/1h37ej5/configuring_the_quick_start_rpi4_when_no_dhcp/",
    "https://www.reddit.com/gallery/1jjyn5q",
    "https://www.reddit.com/r/QNX/comments/14hiegr/identifying_qnx_versionadding_apps/",
    "https://www.reddit.com/r/GPT3/comments/pyo9mr/openai_cli_for_finetuning/",
    "https://www.reddit.com/r/ChatGPT/comments/10nxrcs/chatgpt_vs_openai_playground_vs_gpt3_vs_openai/",
    "https://www.reddit.com/r/QNX/comments/1i0xf9p/qnx_image_ifs_build_tutorials_raspberry_pi4/",
    "https://www.reddit.com/r/LangChain/comments/1hd6w5x/direct_openai_api_vs_langchain_a_performance_and/",       
    "https://www.reddit.com/r/cscareerquestions/comments/1j56ksr/openai_preparing_to_launch_software_developer/",  
    "https://www.reddit.com/r/LocalLLaMA/comments/1fy6j2q/open_webui_openai_api_keys_per_user/",
    "https://www.reddit.com/r/QNX/comments/1h2bf7d/my_first_impressions_of_qnx8_on_the_raspberry_pi4/",
    "https://www.reddit.com/r/ChatGPT/comments/1gv68hc/unnecessarily_credits_in_openai_api_key/",
    "https://www.reddit.com/r/AZURE/comments/1ge09mm/azure_openai_deployments_and_resiliency/",
    "https://www.reddit.com/r/QNX/comments/1je5lic/free_online_qnx_training_now_available/",
    "https://www.reddit.com/r/LocalLLaMA/comments/1i8rujw/notes_on_deepseek_r1_just_how_good_it_is_compared/",     
    "https://www.reddit.com/r/QNX/comments/cqgivb/how_to_access_qnx_file_system_ford_sync/",
    "https://www.reddit.com/r/ChatGPT/comments/14o43y7/chatgpt_in_trouble_openai_sued_for_stealing/",
    "https://www.reddit.com/r/QNX/comments/1h9o14s/boot_loader_hangs_while_booting_a_qnx8_vm_in/",
    "https://www.reddit.com/r/QNX/comments/gjl6f7/migrating_from_qnx_to_linux/",
    "https://www.reddit.com/r/selfhosted/comments/1htiwd1/paperlessai_automated_document_analyzer_for/",
    "https://www.reddit.com/r/n8n/comments/1h5kfdp/n8n_with_openai_api_key_costs/",
    "https://www.reddit.com/r/QNX/comments/1j85ub2/qnx_community_quiz_has_issues/",
    "https://www.reddit.com/r/ChatGPT/comments/17zumpd/hey_disgruntled_openai_employees_leak_the_model/",
    "https://www.reddit.com/r/AI_Agents/comments/1jlvb2d/free_openai_api_alternatives/",
    "https://www.reddit.com/r/Deno/comments/188gw6s/the_official_deno_openai_sdk/",
    "https://www.reddit.com/r/ChatGPTCoding/comments/17h17uu/squeezing_water_from_stone_managing_openai_rate/",    
    "https://www.reddit.com/r/ChatGPT_Pioneers/comments/15aut3i/openai_playground_vs_chat_gpt_a_detailed/",        
]

# Remove duplicate URLs
unique_urls = list(set(urls))

# --- 3) Process each URL to fetch submission details and its comments ---
all_comments_data = []

for url in unique_urls:
    print(f"Processing URL: {url}")
    try:
        # Fetch the submission for the given URL
        submission = reddit.submission(url=url)
        # Load all comments by replacing "more" objects
        submission.comments.replace_more(limit=None)
        comments = submission.comments.list()
        
        # Additional submission-level metadata
        submission_metadata = {
            'submission_id': submission.id,
            'submission_title': submission.title,
            'submission_url': url,
            'submission_score': submission.score,
            'submission_upvote_ratio': submission.upvote_ratio,
            'submission_num_comments': submission.num_comments,
            'submission_subreddit': str(submission.subreddit),
            'submission_is_self': submission.is_self,
            'submission_over_18': submission.over_18
        }
        
        # Collect metadata for each comment and merge with submission metadata
        for comment in comments:
            comment_data = {
                'comment_id': comment.id,
                'parent_id': comment.parent_id,
                'comment_body': comment.body,
                'comment_score': comment.score,
                'comment_gilded': comment.gilded,
                'comment_controversiality': comment.controversiality,
                'comment_edited': comment.edited,
                'comment_created_utc': comment.created_utc,
                'comment_author': str(comment.author),
                'comment_permalink': comment.permalink
            }
            record = {**submission_metadata, **comment_data}
            all_comments_data.append(record)
    except Exception as e:
        print(f"Error processing URL {url}: {e}")

# --- 4) Convert the collected data into a pandas DataFrame ---
df = pd.DataFrame(all_comments_data)

# Convert Unix timestamps to a human-readable datetime if data exists
if not df.empty:
    df['comment_created_utc'] = pd.to_datetime(df['comment_created_utc'], unit='s')

# --- 5) Save the DataFrame to a CSV file ---
csv_filename = 'openai_final.csv'
df.to_csv(csv_filename, index=False)

print(f"\nExtracted {len(df)} comments from {len(unique_urls)} posts.")
print(f"Data has been saved to '{csv_filename}'")
